apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegram-prod
resources:
  - ../../base
# Пароль в prod — через CI. Пример:
# kubectl create secret generic postgres-secret -n telegram-prod \
#   --from-literal=postgres-password=$DB_PASSWORD \
#   --from-literal=postgres-user=support_user \
#   --from-literal=postgres-db=support_bot
