# НЕ КОММИТИТЬ с реальными значениями в Git!
# Заполните перед применением или используйте kubectl create secret.
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: telegram-demo
type: Opaque
stringData:
  bot-token: "1234567890:AAFakeTokenForTestingPurposesOnly123"
  # Контракт с infra: postgres-0.postgres.telegram-demo.svc.cluster.local
  database-url: "postgresql://support_user:dev-password-change-me@postgres-0.postgres.telegram-demo.svc.cluster.local:5432/support_bot"
