apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
