apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | required "postgres.password is required" | quote }}
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-db: {{ .Values.postgres.database | quote }}
